# Generated by Django 4.1.7 on 2023-03-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_following_follow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='action',
        ),
    ]
