# Generated by Django 4.1.7 on 2023-03-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/tweets/%Y/%m/%d'),
        ),
    ]
